# Generated by Django 5.2.4 on 2025-09-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='opcion_pais',
            field=models.CharField(choices=[('argentina', 'Argentina'), ('brasil', 'Brasil'), ('mundo', 'Resto del mundo')], default='pedo', max_length=20),
            preserve_default=False,
        ),
    ]
