# Generated by Django 5.2.4 on 2025-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_compra_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='otro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
