CODIGOS_ISO = {
    'afganistán': 'AF',
    'albania': 'AL',
    'alemania': 'DE',
    'andorra': 'AD',
    'angola': 'AO',
    'anguila': 'AI',
    'antártida': 'AQ',
    'antigua y barbuda': 'AG',
    'arabia saudí': 'SA',
    'argelia': 'DZ',
    'argentina': 'AR',
    'armenia': 'AM',
    'aruba': 'AW',
    'australia': 'AU',
    'austria': 'AT',
    'azerbaiyán': 'AZ',
    'bahamas': 'BS',
    'bangladés': 'BD',
    'barbados': 'BB',
    'baréin': 'BH',
    'bélgica': 'BE',
    'belice': 'BZ',
    'benín': 'BJ',
    'bermudas': 'BM',
    'bielorrusia': 'BY',
    'bolivia': 'BO',
    'bosnia y herzegovina': 'BA',
    'botsuana': 'BW',
    'brasil': 'BR',
    'brunéi': 'BN',
    'bulgaria': 'BG',
    'burkina faso': 'BF',
    'burundi': 'BI',
    'bután': 'BT',
    'cabo verde': 'CV',
    'camboya': 'KH',
    'camerún': 'CM',
    'canadá': 'CA',
    'caribe neerlandés': 'BQ',
    'catar': 'QA',
    'chad': 'TD',
    'chequia': 'CZ',
    'chile': 'CL',
    'china': 'CN',
    'chipre': 'CY',
    'ciudad del vaticano': 'VA',
    'colombia': 'CO',
    'comoras': 'KM',
    'congo': 'CG',
    'corea del sur': 'KR',
    'costa rica': 'CR',
    'côte d’ivoire': 'CI',
    'croacia': 'HR',
    'curazao': 'CW',
    'dinamarca': 'DK',
    'dominica': 'DM',
    'ecuador': 'EC',
    'egipto': 'EG',
    'el salvador': 'SV',
    'emiratos árabes unidos': 'AE',
    'eritrea': 'ER',
    'eslovaquia': 'SK',
    'eslovenia': 'SI',
    'españa': 'ES',
    'estados unidos': 'US',
    'estonia': 'EE',
    'esuatini': 'SZ',
    'etiopía': 'ET',
    'filipinas': 'PH',
    'finlandia': 'FI',
    'fiyi': 'FJ',
    'francia': 'FR',
    'gabón': 'GA',
    'gambia': 'GM',
    'georgia': 'GE',
    'ghana': 'GH',
    'gibraltar': 'GI',
    'granada': 'GD',
    'grecia': 'GR',
    'groenlandia': 'GL',
    'guadalupe': 'GP',
    'guam': 'GU',
    'guatemala': 'GT',
    'guayana francesa': 'GF',
    'guernsey': 'GG',
    'guinea': 'GN',
    'guinea ecuatorial': 'GQ',
    'guinea-bisáu': 'GW',
    'guyana': 'GY',
    'haití': 'HT',
    'honduras': 'HN',
    'hungría': 'HU',
    'india': 'IN',
    'indonesia': 'ID',
    'irak': 'IQ',
    'irlanda': 'IE',
    'isla bouvet': 'BV',
    'isla de la ascensión': 'AC',
    'isla de man': 'IM',
    'islandia': 'IS',
    'islas åland': 'AX',
    'islas caimán': 'KY',
    'islas cook': 'CK',
    'islas feroe': 'FO',
    'islas georgia del sur y sandwich del sur': 'GS',
    'islas malvinas': 'FK',
    'islas pitcairn': 'PN',
    'islas salomón': 'SB',
    'islas turcas y caicos': 'TC',
    'islas vírgenes británicas': 'VG',
    'israel': 'IL',
    'italia': 'IT',
    'jamaica': 'JM',
    'japón': 'JP',
    'jersey': 'JE',
    'jordania': 'JO',
    'kazajistán': 'KZ',
    'kenia': 'KE',
    'kirguistán': 'KG',
    'kiribati': 'KI',
    'kosovo': 'XK',
    'kuwait': 'KW',
    'laos': 'LA',
    'lesoto': 'LS',
    'letonia': 'LV',
    'líbano': 'LB',
    'liberia': 'LR',
    'libia': 'LY',
    'liechtenstein': 'LI',
    'lituania': 'LT',
    'luxemburgo': 'LU',
    'macedonia del norte': 'MK',
    'madagascar': 'MG',
    'malasia': 'MY',
    'malaui': 'MW',
    'maldivas': 'MV',
    'mali': 'ML',
    'malta': 'MT',
    'marruecos': 'MA',
    'martinica': 'MQ',
    'mauricio': 'MU',
    'mauritania': 'MR',
    'mayotte': 'YT',
    'méxico': 'MX',
    'moldavia': 'MD',
    'mónaco': 'MC',
    'mongolia': 'MN',
    'montenegro': 'ME',
    'montserrat': 'MS',
    'mozambique': 'MZ',
    'myanmar (birmania)': 'MM',
    'namibia': 'NA',
    'nauru': 'NR',
    'nepal': 'NP',
    'nicaragua': 'NI',
    'níger': 'NE',
    'nigeria': 'NG',
    'niue': 'NU',
    'noruega': 'NO',
    'nueva caledonia': 'NC',
    'nueva zelanda': 'NZ',
    'omán': 'OM',
    'países bajos': 'NL',
    'pakistán': 'PK',
    'panamá': 'PA',
    'papúa nueva guinea': 'PG',
    'paraguay': 'PY',
    'perú': 'PE',
    'polinesia francesa': 'PF',
    'polonia': 'PL',
    'portugal': 'PT',
    'puerto rico': 'PR',
    'rae de hong kong (china)': 'HK',
    'rae de macao (china)': 'MO',
    'reino unido': 'GB',
    'república centroafricana': 'CF',
    'república democrática del congo': 'CD',
    'república dominicana': 'DO',
    'reunión': 'RE',
    'ruanda': 'RW',
    'rumanía': 'RO',
    'rusia': 'RU',
    'sáhara occidental': 'EH',
    'samoa': 'WS',
    'san bartolomé': 'BL',
    'san cristóbal y nieves': 'KN',
    'san marino': 'SM',
    'san martín': 'MF',
    'san pedro y miquelón': 'PM',
    'san vicente y las granadinas': 'VC',
    'santa elena': 'SH',
    'santa lucía': 'LC',
    'santo tomé y príncipe': 'ST',
    'senegal': 'SN',
    'serbia': 'RS',
    'seychelles': 'SC',
    'sierra leona': 'SL',
    'singapur': 'SG',
    'sint maarten': 'SX',
    'somalia': 'SO',
    'sri lanka': 'LK',
    'sudáfrica': 'ZA',
    'sudán': 'SD',
    'sudán del sur': 'SS',
    'suecia': 'SE',
    'suiza': 'CH',
    'surinam': 'SR',
    'svalbard y jan mayen': 'SJ',
    'tailandia': 'TH',
    'taiwán': 'TW',
    'tanzania': 'TZ',
    'tayikistán': 'TJ',
    'territorio británico del océano índico': 'IO',
    'territorios australes franceses': 'TF',
    'territorios palestinos': 'PS',
    'timor-leste': 'TL',
    'togo': 'TG',
    'tokelau': 'TK',
    'tonga': 'TO',
    'trinidad y tobago': 'TT',
    'tristán de acuña': 'TA',
    'túnez': 'TN',
    'turkmenistán': 'TM',
    'turquía': 'TR',
    'tuvalu': 'TV',
    'ucrania': 'UA',
    'uganda': 'UG',
    'uruguay': 'UY',
    'uzbekistán': 'UZ',
    'vanuatu': 'VU',
    'venezuela': 'VE',
    'vietnam': 'VN',
    'wallis y futuna': 'WF',
    'yemen': 'YE',
    'yibuti': 'DJ',
    'zambia': 'ZM',
    'zimbabue': 'ZW'
}